#!/usr/bin/env bash
set -euo pipefail
repo="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
test_root="$(mktemp -d)"
test_home="$test_root/home with spaces & bars|"
mkdir -p "$test_home"
trap 'rm -rf "$test_root"' EXIT
fake_binary="$test_home/fake-codex-quota-ball"
printf '%s\n' '#!/usr/bin/env bash' 'exit 0' > "$fake_binary"
chmod +x "$fake_binary"
HOME="$test_home" "$repo/scripts/install.sh" "$fake_binary"
test -x "$test_home/.local/bin/codex-quota-ball"
test -f "$test_home/.local/share/applications/codex-quota-ball.desktop"
test -f "$test_home/.local/share/icons/hicolor/scalable/apps/codex-quota-ball.svg"
test -f "$test_home/.config/autostart/codex-quota-ball.desktop"
grep -F "Exec=$test_home/.local/bin/codex-quota-ball" "$test_home/.local/share/applications/codex-quota-ball.desktop"
grep -F "Exec=$test_home/.local/bin/codex-quota-ball" "$test_home/.config/autostart/codex-quota-ball.desktop"
mkdir -p "$test_home/.config/codex-quota-ball"
printf '%s\n' '{"x":1,"y":2}' > "$test_home/.config/codex-quota-ball/config.json"
HOME="$test_home" "$repo/scripts/uninstall.sh"
test ! -e "$test_home/.local/bin/codex-quota-ball"
test ! -e "$test_home/.local/share/applications/codex-quota-ball.desktop"
test ! -e "$test_home/.local/share/icons/hicolor/scalable/apps/codex-quota-ball.svg"
test ! -e "$test_home/.config/autostart/codex-quota-ball.desktop"
test -f "$test_home/.config/codex-quota-ball/config.json"
